//GET ALL

GET http://localhost:3000/holidays

###

// GET BY ID

GET http://localhost:3000/holidays/64aed500f89128711f45bb1b

###


// CREATE
POST http://localhost:3000/holidays
Content-Type: application/json

  {
    "countryName": "Portugal",
    "destination": "Faro",
    "arrivalDate": "2024-04-10",
    "departureDate": "2024-04-16"
  }
###

// DELETE

DELETE http://localhost:3000/holidays/64aebbdec467330a100db369

###

PUT http://localhost:3000/holidays/64aeccf61cdaaf1c66250f14
Content-Type: application/json

{
    "destination": "Tokyo"
}